### ISSUE TITLE
Error for the fraction option on the get scores function 

### ISSUE THREAD

**Issue by fernanda-ordonez** [weissmanlab/decotur#1]
Hello, 

Hope you're doing well. I tried to use Decotur using the fraction option for the close pair method and get the following error, and then I used the get close pairs function on the distance matrix and it worked. I'm not sue if I'm entering the values wrong, and would appreciate if you could help me point out the error. 

Thanks and have a nice day! :)

<img width="1082" alt="Captura de Pantalla 2023-03-06 a la(s) 12 07 13" src="https://user-images.githubusercontent.com/66924998/223017335-fb29f09c-517d-4a9c-b433-68e4928bebcf.png">

**Comment by rohansmehta** [comment]
Hmmmm. That error only shows up after it checks the length of the thing that should be "closepair_params".
I'm going to try to see what's wrong, but does it work if you explicitly assign the correct names to the inputs? Like  "closepair_params = list(0.05, T)"?

**Comment by fernanda-ordonez** [comment]
Hi, I tried with the names and still get the same error. 
<img width="1001" alt="Captura de Pantalla 2023-03-07 a la(s) 10 11 27" src="https://user-images.githubusercontent.com/66924998/223301553-1e86c277-f392-40e7-803e-480f6cd1525c.png">

**Comment by rohansmehta** [comment]
Aaaaah I left a bit of debug code in and that screwed everything up. Try now, it should work.

**Comment by rohansmehta** [comment]
Let me know if I can close this issue!

**Comment by fernanda-ordonez** [comment]
It's solved. Thanks!
